### ISSUE TITLE
help me to build,thank you 

### ISSUE THREAD

**Issue by ddkwork** [perqin/shadowsocks-fyne#1]
main.go:9:2: cannot find module providing package github.com/perqin/shadowsocks-fyne/resources: import lookup disabled by -mod=readonly
	(go.mod file is read-only.)

**Comment by perqin** [comment]
You may need to follow the build steps in Makefile, which only works on Windows now. Have you generated the ./resources/resources_gen.go file?

**Comment by ddkwork** [comment]
@perqin i will try,thank you.
